name: build-dep

on: workflow_dispatch

jobs:
  build-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64/v8
          target: build-dep
          push: true
          tags: ghcr.io/${{ github.repository }}:build-dep
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:build-dep
          cache-to: type=inline
