name: build-image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64/v8
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: 'ghcr.io/${{ github.repository }}:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max

